### PR TITLE
Bumb peerDependency of laravel-elixir to use ^5.0

### LINKED ISSUE #15: Update peerDependencies to use laravel-elixir@5.0
``` bash
npm ERR! peerinvalid The package laravel-elixir@5.0.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer laravel-elixir-livereload@1.1.4 wants laravel-elixir@^4.0
```

### PR DESCRIPTION
**Pull request by wlepinski**
Fixes #15

### CODE REVIEW

**Comment by EHLOVader** [comment]
Should be able to take care of this tonight. 
Doesn't look like the breaking changes made would have any effect on this.

**Comment by EHLOVader** [comment]
Need to rollback my publishing of the NPM module. 1.1.5 needs to stay beta for now. 

Although Laravel-elixir 5.0 was released it wasn't packaged with laravel yet so it needs to wait.

**Comment by EHLOVader** [comment]
So, considering `laravel/laravel` isn't using the newest Elixir version I am keeping 1.1.5 in beta... Please use version `1.1.5-beta1` for now.

**Comment by pongoman** [comment]
Laravel 5.2 uses elixir ^5.0.0.
You can now update the peerDependencies.

**Comment by EHLOVader** [comment]
This was updated a long while ago. But looks like I wasn't published in the stable branch. 

You can still use `1.1.5-beta1` but I will take sometime tonight to publish to npm now that everything is in alignment.

**Pull request merged**
